[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"
[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[cmd_duration]
min_time = 5

[directory]
# prefix = ""
# default format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
# truncation_symbol = ".../"
style = "fg:250"

[username]
# prefix = "upre"
# suffix = "usuf"
format = "[$user]($style)@"
style_user = "fg:8"

[hostname]
# prefix = "hpre"
# suffix = "hsuf"
# default format = "[$hostname]($style) in "
format = "[$hostname]($style)  "
# disabled = true

[git_branch]
# prefix = "gpre"
# suffix = "gsuf"
# default format = "on [$symbol$branch]($style) "
format = " [$symbol$branch]($style) "
style = "fg:177"

[nodejs]
disabled = true
[package]
disabled = true
[php]
disabled = true
